project:
  type: website
  output-dir: docs
  
website:
  title: "Ruby Higdon"
  description: "This is Ruby Higdon's personal blog."
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: lux
    css: styles.css



